### ISSUE TITLE
Icons not colored with default css

### ISSUE THREAD

**Issue by jdhaines** [jaywcjlove/remark-github-blockquote-alert#2]
Hi, thanks for this package!

I'm working with a next.js app and found that when using this plugin as documented my icons were not getting colors.  I'm also using TailwindCSS and it's possible there was a collision of some sort, but I couldn't find one.  I found that adding one more css line to each alert solved the problem.

As an example, adding the highlighted line below for each alert resolved my issue.  I could create a PR adding the 5 lines if that's helpful.

You could also just make a note in the README perhaps to help other people seeing the same problem.

```diff
.markdown-alert.markdown-alert-note .markdown-alert-title {
  color: var(--color-accent-fg);
+  fill: var(--color-accent-fg);
  color: var(--fgColor-accent, var(--color-accent-fg));
}
```

_Before:_ 

![image](https://github.com/jaywcjlove/remark-github-blockquote-alert/assets/3834260/7e1f0bfb-fa7a-4466-809b-1aa3a65f13a8)

_After:_

![image](https://github.com/jaywcjlove/remark-github-blockquote-alert/assets/3834260/0b1bddbe-1583-4bb3-9a4c-009cc18b05ac)

**Comment by jaywcjlove** [comment]
@jdhaines I find it very useful, feel free to submit a PR.

<img width="932" alt="image" src="https://github.com/jaywcjlove/remark-github-blockquote-alert/assets/1680273/ba9df6f3-e836-463b-a3e8-67461c58acc6">


I think adding `fill: currentColor;` to SVG just needs one line of CSS, feel free to submit a PR.


Oh, alternatively, wouldn't it be better if I directly generate it onto the SVG? For example: `<svg fill="currentColor">`

**Comment by jaywcjlove** [comment]
@jdhaines  like this?

```diff
.markdown-alert .markdown-alert-title svg.octicon {
  margin-right: 8px!important;
  margin-right: var(--base-size-8,8px)!important
+  fill: currentColor;
}
```

**Comment by jdhaines** [comment]
I can't say for sure, but it seems like that would work! It seems a simple thing for me to try. Maybe I could add those lines to the package files in the `node_modules` folder and see if I can delete my custom css?

If it won't affect anything negatively, I guess we could just try it on a pre-release version or something too. 

Your call.

**Comment by jaywcjlove** [comment]
@jdhaines Upgrade `v1.2.0`

**Comment by jdhaines** [comment]
Nice, this works as expected.

Initially it didn't, but then I noticed you updated the README with new css.  Once I pasted that in it works great.  Thanks so much!

![image](https://github.com/jaywcjlove/remark-github-blockquote-alert/assets/3834260/d063b34c-f025-42dd-9912-e983240548eb)
